# Generated by Django 5.2.8 on 2025-11-27 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encadreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('specialite', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('matricule', models.CharField(max_length=100, unique=True)),
                ('filiere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('encadreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='soutenances.encadreur')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenances.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('salle', models.CharField(max_length=100)),
                ('jury', models.CharField(max_length=255)),
                ('sujet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='soutenances.sujet')),
            ],
        ),
    ]
