# Generated by Django 5.2.8 on 2025-11-29 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='final_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='sujet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soutenance', to='soutenances.sujet'),
        ),
    ]
