# Generated by Django 5.2.8 on 2025-11-29 19:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenances', '0002_soutenance_final_grade_alter_soutenance_sujet'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soutenance',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('programmee', 'Programmée'), ('realisee', 'Réalisée'), ('validee', 'Validée')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='soutenance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
