# Generated by Django 5.2.8 on 2025-12-09 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenances', '0003_soutenance_created_at_soutenance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='encadreur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soutenances.encadreur'),
        ),
    ]
