# Generated by Django 5.2.8 on 2025-11-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(verbose_name='Commentaire du jury')),
                ('note', models.FloatField(verbose_name='Note obtenue')),
            ],
        ),
    ]
