# Generated by Django 5.2.8 on 2025-11-29 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soutenances', '0002_soutenance_final_grade_alter_soutenance_sujet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(verbose_name='Commentaire du jury')),
                ('note', models.FloatField(verbose_name='Note obtenue')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('soutenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='soutenances.soutenance')),
            ],
        ),
    ]
