# Generated by Django 5.2.8 on 2025-11-27 06:00

import django.db.models.deletion
import rapports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soutenances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=rapports.models.rapport_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('soutenance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='soutenances.soutenance')),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='soutenances.sujet')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
