# Generated by Django 5.2.8 on 2025-12-09 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('soutenances', '0004_alter_sujet_encadreur'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.TextField(default='info'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='soutenances.encadreur'),
        ),
    ]
